default_config:

logger:
  default: info
  logs:
    custom_components.super_soco_custom: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:
