#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

pytest \
    -qq \
    --timeout=9 \
    --durations=10 \
    -n auto \
    --cov custom_components.super_soco_custom \
    --cov-report term-missing \
    -o console_output_style=count \
    -p no:sugar \
    tests