name: Push actions

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  pytest:
    name: "Pytest"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4.1.6"
      - name: Setup Python
        uses: "actions/setup-python@v5.1.0"
        with:
          python-version: "3.12"
      - name: "Install requirements"
        run: python3 -m pip install -r requirements_test.txt
      - name: "Run tests"
        run: |
          pytest \
            -qq \
            --timeout=9 \
            --durations=10 \
            -n auto \
            --cov custom_components.super_soco_custom \
            --cov-report term-missing \
            -o console_output_style=count \
            -p no:sugar \
            tests